### Variables
@baseUrl = http://localhost:5000
@contentType = application/json

### Obtener todos los productos
GET {{baseUrl}}/libros/
Content-Type: {{contentType}}

### Obtener un producto específico por ID
GET {{baseUrl}}/libros/1
Content-Type: {{contentType}}

### Crear un nuevo producto
POST {{baseUrl}}/libros
Content-Type: {{contentType}}

{
    "titulo": " El Alquimista",
    "autor": "Paulo Coelho",
    "isbn": "978-3-16-148410-0",
    "categoria": "Ficción",
    "estado": "prestado"
}

### Eliminar un producto
DELETE {{baseUrl}}/libros/1
Content-Type: {{contentType}}

### Ejemplos adicionales de creación de productos
POST {{baseUrl}}/libros
Content-Type: {{contentType}}

{
    "titulo": "Don Quijote de la Mancha",
    "autor": "Miguel de Cervantes",
    "isbn": "978-3-16-148410-1",
    "categoria": "Novela Clásica",
    "estado": "disponible"
}

###
POST {{baseUrl}}/libros
Content-Type: {{contentType}}

{
    "titulo": "1984",
    "autor": "George Orwell",
    "isbn": "978-3-16-148410-2",
    "categoria": "Distopía",
    "estado": "prestado"
}

###
POST {{baseUrl}}/libros
Content-Type: {{contentType}}

{
    "titulo": "El Gran Gatsby",
    "autor": "F. Scott Fitzgerald",
    "isbn": "978-3-16-148410-3",
    "categoria": "Ficción",
    "estado": "disponible"
} 